import assert from 'node:assert/strict'
import { chromium } from 'playwright-core'

const browser = await chromium.launch({
  executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe',
  headless: true,
  args: ['--no-sandbox', '--disable-gpu', '--disable-dev-shm-usage'],
})
const context = await browser.newContext({ viewport: { width: 1440, height: 900 } })
const page = await context.newPage()
const failures = []
const testProjectName = '星期天与乔治在公园'
page.on('pageerror', error => failures.push(error.message))

try {
  await page.goto('http://127.0.0.1:5173/', { waitUntil: 'domcontentloaded' })
  await page.locator('.curtain-media').waitFor()
  assert.equal(await page.getByAltText(/合上的剧场幕布|逐帧展开的剧场幕布/).count(), 1)
  assert.equal(await page.locator('.curtain-entry video').count(), 0, 'Opening still uses video')
  assert.equal(await page.locator('.curtain-start').count(), 0, 'Opening still requires a click')
  const firstFrame = await page.locator('.curtain-media').getAttribute('src')
  await page.waitForTimeout(220)
  assert.notEqual(await page.locator('.curtain-media').getAttribute('src'), firstFrame, `Opening frames did not advance automatically: ${failures.join('; ')}`)
  assert.equal(await page.locator('.curtain-entry.phase-playing').count(), 1, 'Opening ended before the still sequence')
  await page.getByRole('heading', { name: /Start to Craft/ }).waitFor({ timeout: 60000 })
  await page.evaluate(() => document.fonts.ready)
  assert(await page.evaluate(() => [...document.fonts].some(font => font.family === 'Limelight' && font.status === 'loaded')), 'Limelight display font did not load')
  assert(await page.evaluate(() => [...document.fonts].some(font => font.family === 'Oswald' && font.status === 'loaded')), 'Oswald UI font did not load')
  assert(await page.evaluate(async () => { await document.fonts.load('16px "CangEr YuYangTi W02"', '正文'); return document.fonts.check('16px "CangEr YuYangTi W02"', '正文') }), 'CangEr YuYangTi W02 body font did not load')
  assert(await page.evaluate(async () => { await document.fonts.load('16px "CangEr YuYangTi W05"', '标题'); return document.fonts.check('16px "CangEr YuYangTi W05"', '标题') }), 'CangEr YuYangTi W05 heading font did not load')
  assert.match(decodeURIComponent(await page.locator('.curtain-media').getAttribute('src') || ''), /最终态_最后一帧_|幕布完全展开/)
  await page.waitForTimeout(1150)
  assert.equal(await page.locator('.phase-landing .curtain-media').evaluate(element => getComputedStyle(element).filter), 'brightness(0.3)')
  assert((await page.locator('.curtain-media').evaluate(element => parseFloat(getComputedStyle(element).transitionDuration))) >= 1, 'Final frame lacks a soft brightness transition')
  const actionBoxes = await page.locator('.deco-link').evaluateAll(elements => elements.map(element => element.getBoundingClientRect().toJSON()))
  assert.equal(actionBoxes.length, 2)
  assert(actionBoxes[1].y > actionBoxes[0].bottom, 'Landing actions are not set as two text rows')
  const actionText = page.locator('.deco-link').first().locator('span').nth(1)
  const idleGlow = await actionText.evaluate(element => getComputedStyle(element).textShadow)
  await page.locator('.deco-link').first().hover()
  const activeGlow = await actionText.evaluate(element => getComputedStyle(element).textShadow)
  assert.notEqual(activeGlow, idleGlow, 'Landing text does not light up on hover')
  assert.equal(await page.getByText('Created by SiriZhao, a crazy musical fan.').count(), 1)
  await page.screenshot({ path: 'qa-landing.png', fullPage: true })
  await page.setViewportSize({ width: 910, height: 742 })
  const creditBox = await page.locator('.curtain-credit').boundingBox()
  assert(creditBox && creditBox.y >= 0 && creditBox.y + creditBox.height <= 742, 'Opening credit is outside the viewport')
  assert((await page.evaluate(() => document.documentElement.scrollWidth)) <= 910, 'Opening overflows horizontally at 910px')
  await page.screenshot({ path: 'qa-landing-910.png' })
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.getByRole('button', { name: 'Guidebook' }).click()
  await page.getByRole('heading', { name: /From a blank stage/ }).waitFor()
  await page.getByRole('button', { name: /Begin to Craft/ }).click()
  await page.getByRole('heading', { name: 'My Play' }).waitFor()
  assert.equal(await page.getByText('点击票根以进入排练').count(), 1)
  assert.equal(await page.getByText('A NEW STORY AWAITS').count(), 1)
  assert.match(await page.locator('.play-library-header h1').evaluate(element => getComputedStyle(element).fontFamily), /Limelight/)
  assert.equal(await page.getByText(/STAGE NOTES \/ YOUR REPERTOIRE/).count(), 0)
  assert.equal(await page.getByText(/^\d+ plays?$/).count(), 0)
  assert.match(await page.locator('.play-library').evaluate(element => getComputedStyle(element).backgroundImage), /background/)
  const tuckedTicket = await page.locator('.ticket-card.blank').boundingBox()
  assert(tuckedTicket && Math.abs(tuckedTicket.width / tuckedTicket.height - 2 / 3) < .02, `Ticket does not retain its source ratio: ${tuckedTicket?.width}/${tuckedTicket?.height}`)
  await page.locator('.ticket-folder').hover()
  await page.waitForTimeout(650)
  const exposedTicket = await page.locator('.ticket-card.blank').boundingBox()
  assert(tuckedTicket && exposedTicket && await page.locator('.ticket-scene.is-open').count() === 1, 'Ticket folder did not enter its open state')
  await page.screenshot({ path: 'qa-library.png', fullPage: true })
  await page.setViewportSize({ width: 1100, height: 900 })
  assert((await page.evaluate(() => document.documentElement.scrollHeight)) <= 900, 'Library has a native vertical scrollbar at 1100px')
  await page.screenshot({ path: 'qa-library-1100.png' })
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.locator('.ticket-card.blank .ticket-open-surface').click()
  assert.equal(await page.locator('.stage-option.disabled').count(), 2)
  await page.getByPlaceholder('例如：春之觉醒').fill(testProjectName)
  await page.locator('input[type=number]').first().fill('4')
  await page.getByRole('button', { name: /创建剧目/ }).click()
  await page.getByRole('button', { name: '修改 Scene 名称' }).click()
  await page.getByLabel('Scene 名称').fill('第一幕')
  await page.getByLabel('Scene 名称').press('Enter')
  assert.match(await page.locator('.scene-name').innerText(), /第一幕/)
  await page.getByRole('button', { name: /在幕后/ }).click()
  assert.equal(await page.locator('.editor-page').evaluate(element => getComputedStyle(element).backgroundColor), 'rgb(23, 21, 19)')
  assert.match(await page.locator('.editor-page').evaluate(element => getComputedStyle(element).fontFamily), /Oswald/)
  assert.equal(await page.locator('.stage-actor').count(), 4)
  const initialCanvas = await page.locator('.stage-canvas').boundingBox()
  assert(initialCanvas)
  const canvasWidth = initialCanvas.width
  const workspaceWidth = (await page.locator('.stage-workspace').boundingBox()).width
  assert(canvasWidth / workspaceWidth > .85, `Stage canvas leaves too much unused width: ${canvasWidth}/${workspaceWidth}`)
  assert(Math.abs(initialCanvas.width / initialCanvas.height - 14 / 12) < .04, `Stage aspect ratio is distorted: ${initialCanvas.width}/${initialCanvas.height}`)
  assert.equal(await page.locator('.stage-ruler').count(), 2)
  const sidebarBeforeResize = await page.locator('.object-sidebar').boundingBox()
  const leftResizer = await page.getByRole('separator', { name: '调整左侧舞台对象栏宽度' }).boundingBox()
  assert(sidebarBeforeResize && leftResizer)
  await page.mouse.move(leftResizer.x + leftResizer.width / 2, leftResizer.y + 120)
  await page.mouse.down()
  await page.mouse.move(leftResizer.x + leftResizer.width / 2 + 44, leftResizer.y + 120, { steps: 4 })
  await page.mouse.up()
  await page.waitForTimeout(80)
  const sidebarAfterResize = await page.locator('.object-sidebar').boundingBox()
  assert(sidebarAfterResize && sidebarAfterResize.width > sidebarBeforeResize.width + 35, 'Left workbench divider did not resize the object panel')
  assert(await page.evaluate(() => JSON.parse(localStorage.getItem('musicaldirector-editor-layout-v1') || '{}').left > 260), 'Adjusted workbench panel width was not persisted')
  const resizedCanvas = await page.locator('.stage-canvas').boundingBox()
  assert(resizedCanvas)
  const settledCanvas = await page.locator('.stage-canvas').boundingBox()
  assert(settledCanvas)
  await page.mouse.move(settledCanvas.x + settledCanvas.width / 2, settledCanvas.y + settledCanvas.height / 2)
  assert.match(await page.locator('.stage-coordinate-tooltip').innerText(), /X 0\.0m · Y 6\.0m/)
  const leftRuler = await page.locator('.stage-ruler.left').boundingBox()
  assert(leftRuler)
  await page.mouse.move(leftRuler.x + leftRuler.width / 2, leftRuler.y + leftRuler.height / 4)
  assert.match(await page.locator('.stage-coordinate-tooltip').innerText(), /Y 9\.[01]m/)
  await page.getByRole('button', { name: '收起左侧对象栏' }).click()
  assert((await page.locator('.object-sidebar').boundingBox()).width < 70)
  await page.getByRole('button', { name: '展开左侧对象栏' }).click()
  await page.getByRole('button', { name: '收起右侧信息栏' }).click()
  assert((await page.locator('.inspector').boundingBox()).width < 70)
  await page.getByRole('button', { name: '展开右侧信息栏' }).click()
  await page.getByRole('button', { name: '收起下方动线编排' }).click()
  assert((await page.locator('.timeline-panel').boundingBox()).height < 70)
  await page.getByRole('button', { name: '展开下方动线编排' }).click()
  await page.locator('.object-row').nth(3).getByRole('button', { name: '演员 4', exact: true }).dblclick()
  await page.getByLabel('修改演员 4名称').fill('角色四')
  await page.getByLabel('修改演员 4名称').press('Enter')
  assert.match(await page.locator('.object-row').nth(3).innerText(), /角色四/)
  await page.getByRole('button', { name: '隐藏 角色四' }).click()
  assert.equal(await page.locator('.stage-actor').count(), 3)
  assert.match(await page.locator('.object-row').nth(3).innerText(), /#4/, '隐藏不应使演员下场')
  await page.getByRole('button', { name: '显示 角色四' }).click()
  assert.equal(await page.locator('.stage-actor').count(), 4)
  const leaving = await page.locator('.stage-actor').last().boundingBox()
  assert(leaving)
  await page.mouse.move(leaving.x + leaving.width / 2, leaving.y + leaving.height / 2)
  await page.mouse.down()
  await page.mouse.move(resizedCanvas.x + resizedCanvas.width * .04, resizedCanvas.y + resizedCanvas.height / 2, { steps: 8 })
  assert.equal(await page.getByLabel('松手下场').count(), 1)
  await page.mouse.up()
  assert.equal(await page.locator('.stage-actor').count(), 3)
  assert.match(await page.locator('.object-row').nth(3).innerText(), /不在场/)
  await page.locator('.object-row').nth(3).dragTo(page.locator('.stage-canvas'), { targetPosition: { x: resizedCanvas.width * .8, y: resizedCanvas.height * .7 } })
  assert.equal(await page.locator('.stage-actor').count(), 4)
  await page.locator('.object-row').nth(1).dragTo(page.locator('.stage-canvas'), { targetPosition: { x: resizedCanvas.width * .7, y: resizedCanvas.height * .6 } })
  assert.match(await page.locator('.stage-actor').nth(1).getAttribute('style') || '', /left: (69|70)(?:\.\d+)?%/)
  await page.locator('.stage-actor').first().click()
  await page.locator('.stage-actor').nth(1).click({ modifiers: ['Control'] })
  assert.equal(await page.locator('.stage-actor.selected').count(), 2, 'Actor multi-select did not select both actors')
  const groupBefore = await page.evaluate(() => { const p = JSON.parse(localStorage.getItem('musicaldirector-productions-v1'))[0]; return p.actors.slice(0, 2).map(actor => ({ ...p.positions[0].placements[actor.id] })) })
  const groupAnchor = await page.locator('.stage-actor').first().boundingBox()
  assert(groupAnchor)
  await page.mouse.move(groupAnchor.x + groupAnchor.width / 2, groupAnchor.y + groupAnchor.height / 2)
  await page.mouse.down()
  const dragXs = []
  for (const fraction of [.25, .5, .75, 1]) {
    await page.mouse.move(groupAnchor.x + groupAnchor.width / 2 + 38 * fraction, groupAnchor.y + groupAnchor.height / 2 + 24 * fraction)
    dragXs.push(Number((await page.locator('.stage-actor').first().getAttribute('style'))?.match(/left: ([\d.]+)%/)?.[1]))
  }
  await page.mouse.up()
  assert(dragXs.every((x, index) => index === 0 || x >= dragXs[index - 1] - .05), `Actor jittered while moving: ${dragXs}`)
  const groupAfter = await page.evaluate(() => { const p = JSON.parse(localStorage.getItem('musicaldirector-productions-v1'))[0]; return p.actors.slice(0, 2).map(actor => ({ ...p.positions[0].placements[actor.id] })) })
  assert(Math.abs((groupAfter[0].x - groupBefore[0].x) - (groupAfter[1].x - groupBefore[1].x)) < .2, 'Selected actors did not move together on X')
  assert(Math.abs((groupAfter[0].y - groupBefore[0].y) - (groupAfter[1].y - groupBefore[1].y)) < .2, 'Selected actors did not move together on Y')
  await page.locator('.stage-canvas').click({ position: { x: 350, y: 150 } })
  await page.locator('.stage-actor').first().click()
  await page.mouse.move(1300, 450)
  assert.equal(await page.locator('.inspector-title strong').textContent(), '演员 1')
  assert.equal(await page.getByText('从画布移除').count(), 0)
  assert.equal(await page.getByText('删除手绘轨迹').count(), 0)
  await page.locator('.stage-canvas').click({ position: { x: 350, y: 150 } })
  assert.equal(await page.locator('.inspector-empty').count(), 1)
  await page.locator('.new-position-button').click()
  assert.equal(await page.locator('.position-thumb').count(), 2)
  await page.getByRole('button', { name: '其他新建方式' }).click()
  assert(await page.getByRole('button', { name: '新建空白站位' }).isVisible(), '站位新建菜单被滚动容器裁切')
  await page.getByRole('button', { name: '其他新建方式' }).click()
  assert.equal(await page.locator('.position-thumbs').evaluate(element => getComputedStyle(element).overflowY), 'hidden')
  await page.locator('.position-thumb').first().dragTo(page.locator('.position-thumb').last())
  assert.match(await page.locator('.position-thumb').first().innerText(), /站位 2/, '站位卡拖动未排序')
  await page.locator('.position-thumb').first().dragTo(page.locator('.position-thumb').last())
  assert.match(await page.locator('.position-thumb').first().innerText(), /站位 1/, '站位卡未能拖回')
  await page.locator('.position-thumb').last().locator('button').first().click()
  const actor = page.locator('.stage-actor').first()
  const box = await actor.boundingBox()
  const stage = await page.locator('.stage-canvas').boundingBox()
  assert(box && stage)
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
  await page.mouse.down()
  await page.mouse.move(stage.x + stage.width * .5, stage.y + stage.height * .5, { steps: 8 })
  await page.mouse.up()
  const actorStyle = await actor.getAttribute('style')
  assert(/left: 50(?:\.\d+)?%; top: 50(?:\.\d+)?%/.test(actorStyle || ''), `Actor did not move: ${actorStyle}`)
  const positionPoint = page.locator('.timeline-position').last()
  await positionPoint.scrollIntoViewIfNeeded()
  const pointBox = await positionPoint.boundingBox()
  assert(pointBox)
  await page.mouse.move(pointBox.x + pointBox.width / 2, pointBox.y + pointBox.height / 2)
  await page.mouse.down()
  await page.mouse.move(pointBox.x + pointBox.width / 2 + 100, pointBox.y + pointBox.height / 2, { steps: 8 })
  await page.mouse.up()
  const afterPositionDrag = Number((await page.locator('.transition-bar').innerText()).replace('s', ''))
  assert(afterPositionDrag > 5, `Position did not move in time: ${afterPositionDrag}`)
  const resizeBox = await page.locator('.transition-resize').boundingBox()
  assert(resizeBox)
  await page.mouse.move(resizeBox.x + resizeBox.width / 2, resizeBox.y + resizeBox.height / 2)
  await page.mouse.down()
  await page.mouse.move(resizeBox.x + resizeBox.width / 2 + 50, resizeBox.y + resizeBox.height / 2, { steps: 8 })
  await page.mouse.up()
  const afterTransitionDrag = Number((await page.locator('.transition-bar').innerText()).replace('s', ''))
  assert(afterTransitionDrag > afterPositionDrag, `Transition did not resize: ${afterTransitionDrag}`)
  const collapsedHeight = (await page.locator('.timeline-panel').boundingBox()).height
  await page.locator('.transition-bar').click({ position: { x: 15, y: 15 } })
  const expandedHeight = (await page.locator('.timeline-panel').boundingBox()).height
  assert(expandedHeight > collapsedHeight + 50, `Timeline did not expand: ${collapsedHeight} -> ${expandedHeight}`)
  const workbenchChrome = await page.evaluate(() => {
    const footer = document.querySelector('.canvas-bottom-bar')
    const heading = document.querySelector('.timeline-heading')
    return {
      footerHeight: footer?.getBoundingClientRect().height,
      footerDiamond: footer && getComputedStyle(footer, '::before').content,
      headingDiamond: heading && getComputedStyle(heading, '::before').content,
      headingBorder: heading && getComputedStyle(heading).borderBottomWidth,
      sidebarFootCount: document.querySelectorAll('.sidebar-foot').length,
    }
  })
  assert(workbenchChrome.footerHeight <= 52 && workbenchChrome.footerDiamond === 'none' && workbenchChrome.headingDiamond === 'none' && workbenchChrome.headingBorder !== '0px' && workbenchChrome.sidebarFootCount === 0, `Workbench dividers or compact controls regressed: ${JSON.stringify(workbenchChrome)}`)
  assert((await page.locator('.stage-canvas').boundingBox()).height > 280, 'Expanded timeline makes the stage too short to edit')
  assert.equal(await page.locator('.movement-row').count(), 4)
  await page.getByTitle('添加演员').click()
  assert.equal(await page.locator('.movement-row').count(), 4, 'An actor absent from both positions appeared in Transition')
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '删除 演员 5' }).click()
  assert.equal(await page.locator('.object-row:not(.stage-mark-row)').count(), 4)
  assert.equal(await page.getByLabel('走位时间').count(), 1)
  await page.screenshot({ path: 'qa-timeline.png', fullPage: true })
  const endHandle = page.locator('.movement-row').first().locator('[data-part=end]')
  await endHandle.scrollIntoViewIfNeeded()
  const handleBox = await endHandle.boundingBox()
  assert(handleBox)
  await page.mouse.move(handleBox.x + handleBox.width / 2, handleBox.y + handleBox.height / 2)
  await page.mouse.down()
  await page.mouse.move(handleBox.x + handleBox.width / 2 - 80, handleBox.y + handleBox.height / 2, { steps: 8 })
  await page.mouse.up()
  const endTime = Number(await page.locator('.movement-row').first().getByLabel('演员 1 结束时间').inputValue())
  assert(endTime < afterTransitionDrag, `Movement did not resize: ${endTime}`)
  const movementBar = page.locator('.movement-row').first().locator('.movement-bar')
  await movementBar.scrollIntoViewIfNeeded()
  const movementBox = await movementBar.boundingBox()
  assert(movementBox)
  await page.mouse.move(movementBox.x + movementBox.width / 2, movementBox.y + movementBox.height / 2)
  await page.mouse.down()
  await page.mouse.move(movementBox.x + movementBox.width / 2 + 40, movementBox.y + movementBox.height / 2, { steps: 8 })
  await page.mouse.up()
  const startTime = Number(await page.locator('.movement-row').first().getByLabel('演员 1 开始时间').inputValue())
  assert(startTime > 0, `Movement bar did not move: ${startTime}`)
  assert.match(await page.locator('.movement-row').first().locator('.movement-bar').innerText(), /默认动线/)
  await page.locator('.movement-row').first().getByRole('button', { name: '编辑动线' }).click()
  assert.equal(await page.locator('.stage-path-overlay .curve-preview').count(), 1)
  assert.equal(await page.getByRole('toolbar', { name: '动线绘制工具' }).count(), 1)
  assert.equal(await page.locator('.canvas-tools').getByRole('button', { name: '曲线点' }).count(), 0)
  await page.getByRole('button', { name: '直线 / 折点' }).click()
  assert.equal(await page.getByRole('toolbar', { name: '动线绘制工具' }).count(), 1, 'Selecting a path tool exits movement editing')
  const line = page.locator('.path-hitline')
  const stageForPath = await page.locator('.stage-canvas').boundingBox()
  const ends = await page.evaluate(() => { const p = JSON.parse(localStorage.getItem('musicaldirector-productions-v1'))[0]; const actor = p.actors[0].id; return [p.positions[0].placements[actor], p.positions[1].placements[actor]] })
  const clickPath = ratio => page.mouse.click(stageForPath.x + stageForPath.width * (ends[0].x + (ends[1].x - ends[0].x) * ratio) / 100, stageForPath.y + stageForPath.height * (ends[0].y + (ends[1].y - ends[0].y) * ratio) / 100)
  await clickPath(.35)
  assert.equal(await page.locator('.path-anchor.corner').count(), 1)
  await page.getByRole('button', { name: '曲线点' }).click()
  await clickPath(.75)
  assert.equal(await page.locator('.path-anchor.smooth').count(), 1)
  assert.equal(await page.locator('.curve-handle').count(), 2)
  const curveBefore = await page.locator('.stage-path-overlay .curve-preview').getAttribute('points')
  const curveHandle = page.getByRole('button', { name: '节点 2 入曲线手柄' })
  await curveHandle.scrollIntoViewIfNeeded()
  const curveBox = await curveHandle.boundingBox()
  assert(curveBox)
  await page.mouse.move(curveBox.x + curveBox.width / 2, curveBox.y + curveBox.height / 2)
  await page.mouse.down()
  await page.mouse.move(curveBox.x + curveBox.width / 2 + 55, curveBox.y + curveBox.height / 2 - 45, { steps: 8 })
  await page.mouse.up()
  const curveAfter = await page.locator('.stage-path-overlay .curve-preview').getAttribute('points')
  assert.notEqual(curveAfter, curveBefore)
  assert.match(await page.locator('.movement-row').first().locator('.movement-bar').innerText(), /自定义动线/)
  const curvedPlaybackDistance = await page.evaluate(async projectName => {
    const { placementAt } = await import('/src/model.ts')
    const production = JSON.parse(localStorage.getItem('musicaldirector-productions-v1') || '[]').find(item => item.name === projectName)
    const objectId = production.actors[0].id
    const start = production.positions[0].placements[objectId]
    const end = production.positions[1].placements[objectId]
    const movement = production.transitions[0].movements[objectId]
    const middle = placementAt(production, movement.offset + movement.duration / 2)[objectId]
    return Math.hypot(middle.x - (start.x + end.x) / 2, middle.y - (start.y + end.y) / 2)
  }, testProjectName)
  assert(curvedPlaybackDistance > .5, `Preview did not follow the edited curve: ${curvedPlaybackDistance}`)
  await page.screenshot({ path: 'qa-curve-editor.png', fullPage: true })
  await page.getByRole('button', { name: '完成编辑' }).click()
  const actorFour = page.getByRole('button', { name: /角色四，/ })
  const actorFourBox = await actorFour.boundingBox()
  assert(actorFourBox)
  await page.mouse.move(actorFourBox.x + actorFourBox.width / 2, actorFourBox.y + actorFourBox.height / 2)
  await page.mouse.down()
  await page.mouse.move(stageForPath.x + stageForPath.width * .04, actorFourBox.y, { steps: 6 })
  assert.equal(await page.getByLabel('松手下场').count(), 1, 'Dragging into a side-stage zone should offer offstage state')
  await page.mouse.up()
  await page.locator('.position-thumb').first().locator('button').first().click()
  const actorFourRow = page.locator('.movement-row').filter({ hasText: '角色四' })
  assert.equal(await actorFourRow.count(), 1, 'An actor present at either end is missing from Transition')
  assert.equal(await actorFourRow.getByRole('button', { name: '编辑动线' }).isDisabled(), false, 'An offstage transition cannot be edited')
  await actorFourRow.getByRole('button', { name: '编辑动线' }).click()
  await page.getByRole('toolbar', { name: '动线绘制工具' }).getByRole('button', { name: '选择', exact: true }).click()
  assert.equal(await page.getByRole('toolbar', { name: '动线绘制工具' }).count(), 1, 'Selecting a path tool exits an offstage transition')
  assert.equal(await page.getByLabel('左侧下场区域').count(), 1)
  assert.match(await page.locator('.curve-endpoint').last().getAttribute('style') || '', /left: 4%/, 'Offstage endpoint is not placed in the side-stage zone')
  await page.screenshot({ path: 'qa-offstage-path.png', fullPage: true })
  await page.getByRole('button', { name: '完成编辑' }).click()
  await page.getByRole('button', { name: '切换网格' }).click()
  assert.equal(await page.locator('.stage-canvas.grid-hidden').count(), 1)
  await page.getByRole('button', { name: '切换 Stage Mark' }).click()
  assert.equal(await page.locator('.stage-mark').count(), 0)
  await page.getByRole('button', { name: '切换 Stage Mark' }).click()
  await page.getByRole('button', { name: '解锁舞台标记' }).click()
  const mainCurtain = page.getByRole('button', { name: '舞台标记 大幕' })
  await page.locator('.toast').waitFor({ state: 'hidden' })
  await mainCurtain.scrollIntoViewIfNeeded()
  const markBox = await mainCurtain.boundingBox()
  assert(markBox)
  assert.match(await mainCurtain.getAttribute('class') || '', /is-editable/, 'Stage mark lock did not unlock editing')
  assert.equal(await page.evaluate(({ x, y }) => document.elementFromPoint(x, y)?.getAttribute('aria-label'), { x: markBox.x + markBox.width / 2, y: markBox.y + markBox.height / 2 }), '舞台标记 大幕', 'Stage mark is covered by another canvas layer')
  const beforeMarkStyle = await mainCurtain.getAttribute('style')
  await page.mouse.move(markBox.x + markBox.width / 2, markBox.y + markBox.height / 2)
  await page.mouse.down()
  assert.equal(await page.getByLabel('舞台标记名称').count(), 1, 'Unlocked stage mark did not select')
  await page.mouse.move(markBox.x + markBox.width / 2, markBox.y - 28, { steps: 5 })
  await page.mouse.up()
  await page.waitForTimeout(100)
  assert.notEqual(await mainCurtain.getAttribute('style'), beforeMarkStyle, 'Unlocked stage mark did not move on canvas')
  assert.equal(await page.getByLabel('舞台标记名称').inputValue(), '大幕')
  await page.screenshot({ path: 'qa-stage-marks.png', fullPage: true })
  await page.locator('.position-thumb').first().locator('button').first().click()
  const nextBefore = await page.locator('.next-button').boundingBox()
  await page.locator('.next-button').click()
  await page.waitForTimeout(300)
  const nextDuring = await page.locator('.next-button').boundingBox()
  assert(nextBefore && nextDuring && Math.abs(nextBefore.x - nextDuring.x) < 1 && Math.abs(nextBefore.width - nextDuring.width) < 1, 'Next button moved during playback')
  assert.equal(await page.getByRole('progressbar', { name: '播放进度' }).count(), 0, 'Rehearsal Next should not show a progress line')
  assert.equal(await page.locator('.play-time').count(), 0)
  await page.keyboard.press('Space')
  assert.match(await page.locator('.position-thumb.active').innerText(), /站位 2/)
  await page.locator('.position-thumb').first().locator('button').first().click()
  await page.locator('.stage-actor').first().click()
  await page.keyboard.press('Space')
  assert.match(await page.locator('.next-button').innerText(), /直接到位/)
  await page.keyboard.press('Space')
  assert.match(await page.locator('.position-thumb.active').innerText(), /站位 2/)
  await page.getByRole('button', { name: '预演模式' }).click()
  assert.equal(await page.getByRole('progressbar', { name: '播放进度' }).count(), 1, 'Preview playback should show progress')
  await page.getByTitle('从头重播').click()
  await page.getByRole('button', { name: '播放', exact: true }).click()
  await page.getByRole('button', { name: '暂停', exact: true }).click()
  await page.getByRole('button', { name: '排练模式' }).click()
  await page.getByTitle('添加道具').click()
  await page.locator('.add-prop-options').getByRole('button', { name: '长方形' }).click()
  assert.equal(await page.locator('.stage-prop').count(), 1)
  await page.getByTitle('添加道具').click()
  await page.locator('.add-prop-options').getByRole('button', { name: '圆形', exact: true }).click()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '删除 道具 2' }).click()
  assert.equal(await page.locator('.stage-prop').count(), 1)
  await page.getByRole('button', { name: '舞台参数' }).click()
  assert.equal(await page.getByRole('button', { name: /添加参考线/ }).count(), 0)
  await page.getByRole('button', { name: '完成' }).click()
  await page.getByRole('button', { name: '添加舞台标记' }).click()
  assert.equal(await page.locator('.stage-mark-row').count(), 6)
  assert.match(await page.getByLabel('舞台标记名称').inputValue(), /参考线/)
  const wav = Buffer.alloc(44 + 8000)
  wav.write('RIFF', 0); wav.writeUInt32LE(wav.length - 8, 4); wav.write('WAVEfmt ', 8)
  wav.writeUInt32LE(16, 16); wav.writeUInt16LE(1, 20); wav.writeUInt16LE(1, 22)
  wav.writeUInt32LE(8000, 24); wav.writeUInt32LE(8000, 28); wav.writeUInt16LE(1, 32)
  wav.writeUInt16LE(8, 34); wav.write('data', 36); wav.writeUInt32LE(8000, 40)
  wav.fill(128, 44)
  await page.locator('.timeline-actions input[type=file]').first().setInputFiles([{ name: 'rehearsal.wav', mimeType: 'audio/wav', buffer: wav }, { name: 'second.wav', mimeType: 'audio/wav', buffer: wav }])
  await page.locator('.music-clip').nth(1).waitFor()
  const uploadedClips = await page.evaluate(() => JSON.parse(localStorage.getItem('musicaldirector-productions-v1'))[0].music)
  assert(uploadedClips[1].start >= uploadedClips[0].start + uploadedClips[0].duration, 'Uploading two songs creates overlapping clips')
  await page.locator('.music-clip').nth(1).getByTitle('音乐操作').click()
  await page.getByRole('button', { name: '删除音乐' }).click()
  assert.equal(await page.locator('.music-clip').count(), 1)
  await page.locator('.music-clip').getByTitle('音乐操作').click()
  assert(await page.getByRole('button', { name: '删除音乐' }).isVisible(), 'Short music clips hide their actions')
  const musicMenuBox = await page.locator('.music-clip-menu').boundingBox()
  assert(musicMenuBox && musicMenuBox.width >= 140, 'Music actions are clipped inside a short clip')
  await page.screenshot({ path: 'qa-music-menu.png', fullPage: true })
  await page.getByRole('button', { name: '重命名' }).click()
  await page.getByLabel('音乐名称').fill('排练配乐')
  await page.getByLabel('音乐名称').press('Enter')
  assert.match(await page.locator('.music-clip').innerText(), /排练配乐/)
  await page.reload({ waitUntil: 'domcontentloaded' })
  await page.getByRole('button', { name: /Begin to Craft/ }).click()
  await page.locator('.ticket-folder').hover()
  await page.waitForTimeout(650)
  await page.screenshot({ path: 'qa-library-with-play.png', fullPage: true })
  await page.getByRole('button', { name: '打开剧目 ' + testProjectName }).click()
  assert.equal(await page.locator('.position-thumb').count(), 2)
  assert.equal(await page.locator('.stage-actor').count(), 4)
  assert.equal(await page.locator('.music-clip').count(), 1)
  await page.locator('.transition-bar').click({ position: { x: 15, y: 15 } })
  assert.match(await page.locator('.movement-row').first().locator('.movement-bar').innerText(), /自定义动线/)
  await page.locator('.movement-row').first().getByRole('button', { name: '编辑动线' }).click()
  assert.equal(await page.locator('.path-anchor').count(), 2)
  assert.equal(await page.locator('.stage-path-overlay .curve-preview').getAttribute('points'), curveAfter)
  await page.getByRole('button', { name: '完成编辑' }).click()
  await page.screenshot({ path: 'qa-editor.png', fullPage: true })
  const mobile = await context.newPage()
  mobile.on('pageerror', error => failures.push(error.message))
  await mobile.setViewportSize({ width: 800, height: 900 })
  await mobile.goto('http://127.0.0.1:5173/', { waitUntil: 'domcontentloaded' })
  await mobile.getByRole('button', { name: /Begin to Craft/ }).click()
  await mobile.locator('.ticket-folder').click()
  await mobile.getByRole('button', { name: '打开剧目 ' + testProjectName }).click()
  assert((await mobile.locator('.object-sidebar').boundingBox()).width < 70)
  assert((await mobile.locator('.inspector').boundingBox()).width < 70)
  assert((await mobile.locator('.timeline-panel').boundingBox()).height < 70)
  assert((await mobile.evaluate(() => document.documentElement.scrollWidth)) <= 800, 'Mobile layout overflows horizontally')
  await mobile.screenshot({ path: 'qa-mobile.png', fullPage: true })
  await mobile.setViewportSize({ width: 390, height: 844 })
  assert((await mobile.evaluate(() => document.documentElement.scrollWidth)) <= 390, 'Phone layout overflows horizontally')
  await mobile.screenshot({ path: 'qa-phone.png', fullPage: true })
  await mobile.close()
  await page.getByRole('button', { name: '返回剧目列表' }).click()
  await page.locator('.ticket-folder').hover()
  await page.waitForTimeout(650)
  const filledTicket = await page.locator('.ticket-card:not(.blank)').boundingBox()
  assert(filledTicket && Math.abs(filledTicket.width / filledTicket.height - 2 / 3) < .02, `Filled ticket lost its source ratio: ${filledTicket?.width}/${filledTicket?.height}`)
  const ticketCopyFits = await page.locator('.ticket-card:not(.blank) .ticket-content strong').evaluate(element => element.scrollWidth <= element.clientWidth && element.scrollHeight <= element.clientHeight)
  const ticketDetailFits = await page.locator('.ticket-card:not(.blank) .ticket-detail').evaluate(element => element.scrollWidth <= element.clientWidth)
  const ticketTitleContained = await page.locator('.ticket-card:not(.blank) .ticket-content strong').evaluate(element => {
    const title = element.getBoundingClientRect()
    const body = element.closest('.ticket-body').getBoundingClientRect()
    return title.left >= body.left - 1 && title.right <= body.right + 1 && title.top >= body.top - 1 && title.bottom <= body.bottom + 1
  })
  assert(ticketCopyFits && ticketDetailFits && ticketTitleContained, 'Ticket title or detail overflows its printed safe area')
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '删除剧目' }).click()
  assert.equal(await page.locator('.ticket-card.is-deleting').count(), 1, 'Confirmed deletion does not start the ticket tear animation')
  await page.waitForTimeout(820)
  assert.equal(await page.getByRole('button', { name: '打开剧目 ' + testProjectName }).count(), 0, 'Deleted ticket remains in the library')
  assert.equal(JSON.parse(await page.evaluate(() => localStorage.getItem('musicaldirector-productions-v1') || '[]')).length, 0, 'Deleted production remains persisted')
  assert.deepEqual(failures, [])
  console.log('E2E passed: opening, ticket fitting/deletion, library, visibility/offstage drag, position sorting, aspect/rulers, panels, timing, filtered movements, path nodes, Next/Space/progress, music, persistence, mobile layout')
} finally {
  await context.close()
  await browser.close()
}
